from . import clinic_portal_tile
from . import clinic_document
from . import clinic_document_acknowledgement
from . import stock_picking
from . import stock_picking_type
from . import stock_move
from . import stock_location
from . import purchase_order
from . import res_config_settings
from . import product_product
from . import product_template
from . import res_users
from . import stock_discrepancy
from . import product_pricelist
from . import ir_http
from . import cashier_session
from . import kiosk_access_log
from . import clinic_workstation
from . import consumption_ledger
from . import sale_order
from . import drug_sync_service
from . import drug_dosage_form
from . import drug_openmrs_concept
from . import clinic_prescription
from . import clinic_inventory